http:
  port: 3000

redis:
  host: 'localhost'
  port: 6379

file:
  repository: 
      original: /Users/verybuck/Documents/repository/image_crop/original
      resizing: /Users/verybuck/Documents/repository/image_crop/resizing
      cropped: /Users/verybuck/Documents/repository/image_crop/cropped
      pdf: /Users/verybuck/Documents/repository/image_crop/pdf
  size: #A4
    width: 595 #595.28
    height: 841 #841.89